### ISSUE TITLE
Maps full width of the viewable window (vw)

### ISSUE THREAD

**Issue by bryanisles** [therealizzi/earworm#1]
For the div that is the wrapper for the map:
<pre>
<code>
   &lt;div class="container" style="width:500px; height:500px;"&gt;
</code>
</pre>

,change the div to: 
<pre>
<code>
   &lt;div id="maps-wrapper" class="container"&gt;
</code>
</pre>

,then in the css file style.css keep the following:
<pre>
<code>
   #map{height:100%; width:100%;}
</code>
</pre>

,but add the following after the following:
<pre>
<code>
   #maps-wrapper{width:100%; height:510px; padding:0; margin:0;}
</code>
</pre>

,and add the following media query:
<pre><code>
  @media only screen and (max-width: 992px) {
    .pastMax {
        max-height:none;
        height:auto;
    }
    #map {
        width: 100vw;
    }
    #maps-wrapper {
        width:100vw;
    }
  }
</code></pre>

the aforementioned code should make the map full width in the mobile mode or when the width of the screen is 992px or less

this also removes the scrollbar in the 'mobile mode' as well and extends it to the bottom of the content

let me know if you have any questions in regards to the above code

**Comment by therealizzi** [comment]
FIXED
